### ISSUE TITLE
[TX-Builder] Provide feedback when we can't parse a JSON from an input

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#143]
When parsing inputs in transaction builder we have a JSON.parse outside a try-catch. As JSON.parse can throw when parsed value is not a valid JSON we should catch this scenario and show an error to the user, instead of simply not allowing to add the transaction and printing an error in the console

![image](https://user-images.githubusercontent.com/25051234/124490852-e1f85e80-ddb2-11eb-8bcb-cf724c4ff903.png)

**Comment by dasanra** [comment]
We added a general try-catch to show user an error without specific feedback, so at least they know that something is happening. Still we should improve input feedback
https://github.com/gnosis/safe-react-apps/pull/142#discussion_r663998436

**Comment by mikhailxyz** [comment]
This issue is no longer present after the parser overhaul by Dani. Can be tested on development
![image](https://user-images.githubusercontent.com/16622558/176183272-56f182b9-35ba-43dd-bd4d-93e2d465ba8c.png)

**Comment by JagoFigueroa** [comment]
True, closing this ticket ;)
