### ISSUE TITLE
Support EIP-712 messages for signing

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-react-apps#255]
## Overview
Some apps such as snappshot.org told us they'd like to sign EIP-712 messages with the Safe. Currently, we only support hashes/raw messages via eth_sign or personal_sign

## Goals
Support EIP-712 messages

## Requirements
- Support EIP-712 messages in the apps sdk
- Support EIP-712 messages on the interface leve

## Links
https://eips.ethereum.org/EIPS/eip-712

**Comment by mikhailxyz** [comment]
An overview of what's needs to be done to support this:
We already have a signing mechanism in place for `personal_sign` and `eth_sign`. The only difference with EIP-712 is that these signing methods receive a hash to sign or a raw message that we then hash using EIP-191. On the contract level, everything stays the same. We still call `signMessage` with a `bytes32`. The main difference is the hash generation. EIP-712 implements some rules around it. You can read low-level details about how the hash is generated in the proposal. Code example can be found here: https://github.com/safe-global/safe-contracts/blob/main/src/utils/execution.ts#L68-L70

Integration steps:
- Add a handler for EIP712 message similar to `signMessage` in the Safe interface. You can probably reuse the same handler and then branch depending on the message type
- Add a method for signing to the `safe-apps-sdk`
- Add `JSON-RPC` method support to `safe-apps-provider`
- Add support to the Walletconnect Safe app

**Comment by ennisjo** [comment]
Gitcoin bounty document - https://docs.google.com/document/d/1GIZ97iSX3wyzle9aXnEhcMnL8__2zYIE0byTz6fVNxM/edit#

**Comment by ennisjo** [comment]
Bounty is up - https://gitcoin.co/issue/29229

**Comment by JagoFigueroa** [comment]
Like with this [ticket](https://github.com/safe-global/safe-react/issues/4027) I think we can close this one as well. Cheers!

**Comment by real-hansolo** [comment]
Hey @JagoFigueroa , the link to the ticket you mention is broken. What this feature ultimately implemented?

**Comment by mmv08** [comment]
It was implemented

**Comment by mmv08** [comment]
https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-sdk#off-chain-signing
