### ISSUE TITLE
[Desktop app + safe-apps] asset swapping apps (Uniswap & Sushi) not working as expected

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#277]
## Description
Safe assets do not load when operating with apps like Uniswap or Sushi on the desktop app via Trezor and Ledger.

## Environment
 - Wallet: Trezor & Ledger
 - Environment: tested in https://github.com/gnosis/safe-react/actions/runs/1693347662 mainnet
 - Trezor version: 1.10.4
 - Ledger version: 2.1.0

## Steps to reproduce
 1. Go to the list of available apps and open these apps.
 2. Check safe funds in the app

## Expected result
Apps should be usable.

## Obtained result
Safe assets do not load so it can't be swapped in any way

**Comment by yagopv** [comment]
Debugging  the production build seems to be an error in an infura call without key

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/1576776/158592171-70cebdb9-cccb-4426-9ac0-bc45437daf7b.png">

```
curl 'https://rinkeby.infura.io/v3/' -H 'authority: rinkeby.infura.io' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) old-airport-include/1.0.0 Chrome Electron/13.5.2 Safari/537.36' -H 'content-type: application/json' -H 'accept: */*' -H 'origin: https://localhost:5002' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'sec-fetch-dest: empty' -H 'referer: https://localhost:5002/' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB' --data-binary '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":"1"}' --compressed
```

If I rewrite the call to add the key using a proxy then seems to load properly (But different assets than the web 🤔).

**Comment by dasanra** [comment]
The new release should fix this
https://github.com/safe-global/safe-react/releases/tag/v3.33.2%2Bdesktop
