### ISSUE TITLE
[Safe Apps] Share Safe Apps through URL deeplinking

### ISSUE THREAD

**Issue by lukasschor** [safe-global/safe-react-apps#322]
# Why do we need this?

As a Safe App developer I want to promote my Safe App so that I don't rely on Gnosis to include it in the default apps list for user to be able to use my Safe App.

As a user I want to easily add new apps that are recommended to me by friends or directly by Safe apps developers so that I can easily try out new apps being built.

# What is this about?

Third-party developers need an easy way to promote their Safe Apps without us listing their Safe App in the default list. 

We should enable to create a link for a given loaded Safe App, that when opened by another user, would check if this app is already loaded and, if not, open the Add Custom App modal with the URL already pre-filled.

**Comment by dasanra** [comment]
Solved here https://github.com/safe-global/safe-pm/issues/60
