### ISSUE TITLE
Add tooltips describing a Safe App's functionality

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#331]
## Description
Although there is a small description per app on the main app screen, a tooltip with more detailed info about what each app does could come a long way in terms of accessibility for end users.

This could be something specially useful for third party apps as their description can be a bit cryptic, providing 0 functional feedback.

**Comment by dasanra** [comment]
This can be considered close with the new drawer implementation
https://github.com/safe-global/web-core/issues/1414
