### ISSUE TITLE
Adjust walletconnect app to support ethers `.wait` method

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-react-apps#377]
## Overview
If you submit a transaction with ethers.js and call the `wait` method to wait when the transaction is merged, the promise [will never resolve](https://ethereum.stackexchange.com/questions/123473/gnosis-safe-transaction-promises-fail-resolve). This can be worked around storing a faking transaction and using it with `eth_getTransactionByHash` as we do in `safe-apps-provider` https://github.com/gnosis/safe-apps-sdk/blob/master/packages/safe-apps-provider/src/provider.ts#L78-L90

## Goals
Support `ethers.js` wait in walletconnect Safe App

## Requirements
To be decided collectively. It can solved by migrating to safe-apps-provider or simply adjusting app code

## Links
more context: https://gnosisinc.slack.com/archives/CQB729LLF/p1647009035421679

**Comment by nicosampler** [comment]
Hi There, any plans to prioritize this issue? All the apps that allow connecting with the safe through WC (and ethersjs) are experiencing this issue, it is needed to refresh the page in order to get the new status after sending a tx.
