### ISSUE TITLE
Update styles Safe App list cards

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#413]
## Overview
Lila also proposed an improvement on Safe Apps card design, in order to display more information allowing us to check more apps at one sight

## Goals
Implement the new designs for the Safe Apps card.

Be aware that web team already implemented a component for this new styling on the Dashboard component that is meant to show Safe Apps. We can just replicate the styles taking this as reference. It would be nice to also use the same component in the Dashboard later

## Requirements

- Adapt current Safe Apps card to new style
- If possible once our changes are merged change the Dashboard Safe App card by the same component that we update

## Screens

[Figma Designs](https://www.figma.com/file/v56CKWh6Yp60cSsZ71URB0/dApp-sharing-functionality?node-id=1%3A111)

![imagen](https://user-images.githubusercontent.com/25051234/161080397-41f47bea-61a3-491b-9b32-0a8042c63fe0.png)

## Links
#414

**Comment by JagoFigueroa** [comment]
For this one I will be leaving all the design approval to our magician @liliiaorlenko :pepe-swag:

https://pr3804--safereact.review-safe.gnosisdev.com/app/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/apps

A very small note from my end regarding the labels that are displayed when hovering the share / bookmark buttons.

<img width="332" alt="Screenshot 2022-04-29 at 10 12 19" src="https://user-images.githubusercontent.com/92332710/165907805-98820124-b242-499b-965f-43b00dabea3b.png">

What about changing the bookmark one from: 

- Pin from Safe Apps / Unpin from Safe Apps

To:

- Pin as a bookmarked app / Unpin as a bookmarked app (or something like that?)

Cheers!
