### ISSUE TITLE
Allow the user to select a Safe that is already in local storage

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#416]
## Overview
When an user that already owns a Safe gets to a Safe App landing page we should allow to select from the Safes he owns already.

## Goals
Create a component that allows the user to select a specific Safe to use when opening a Safe App direct link. Specific logic to different scenarios will be detailed in Requirements section

## Requirements
- If we can detect the Safe App on our config service:
  - Add to the component all Safes that the user have configured that are compatible with all chains where we know the Safe App is available
  - Even if the provided query param chainId is not assigned in the Safe Apps list to this app, we will show Safes that may have on this chain suggested by the query param.
  - If the user have a Safe on the query param chainId select by default the latest used Safe in this chain
  - If the user don't have any Safe on the query param chainId fallback to a latest used safe on a chain where we know the app is available
- If we can't find the app on our configuration display all user Safes:
  - First fallback to last used Safe in the chain selected by query param 
  - If the user has no Safe in that chain select by default last chain and Safe used. In this case would be good to show a warning that selected safe chain is not matching suggested chain.

## Screens
 - [Figma](https://www.figma.com/file/v56CKWh6Yp60cSsZ71URB0/dApp-sharing-functionality?node-id=1%3A1542)
![imagen](https://user-images.githubusercontent.com/25051234/161094462-cada7047-4618-467b-968d-f771be1504db.png)
![imagen](https://user-images.githubusercontent.com/25051234/161094580-d4e56715-b281-45de-ab1d-7295a15f5ff2.png)

## Links
#414

**Comment by mikheevm** [comment]
A couple of requirements are not clear to me:
> Even if the selected query param chainId is not on our service we will add Safes that may have on this chain we didn't yet registered on our config service.

What does it mean? I understood it as if the chainID is not supported by the Safe (that's the equivalent of it not being on the config service), we should still get Safes from somewhere. I'm not sure if we can do it and what's the motivation behind it because the services won't support that chain anyway.

> If the user don't have any Safe on the query param chainId fallback to a latest used safe on a chain where we know the app is available

Does it mean even a non-owned Safe?

> Select by default the safe used in last chain

This should be `safe on the chain in chainID query param` instead of `last chain`, right?

**Comment by dasanra** [comment]
> What does it mean? I understood it as if the chainID is not supported by the Safe (that's the equivalent of it not being on the config service), we should still get Safes from somewhere. I'm not sure if we can do it and what's the motivation behind it because the services won't support that chain anyway.

I meant if in the Safe Apps list config service, that app don't have the query parameter chain Id associated. Didn't mean a chain not supported by the Safe web at all

> Does it mean even a non-owned Safe?

By default, yes. In most of the cases we will fallback to a safe that is used regularly by the user. We can refine later if needed.

> This should be `safe on the chain in chainID query param` instead of `last chain`, right?

Correct, I'll update the description to be more explicit

I will also update the other cases where is not that clear
