### ISSUE TITLE
[TX-Builder] Arrays with long numbers cause overflow

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#440]
## Description
When inputing an array of long numbers without wrapping as string they cause overflow.

This needs to be tested on an input that gets an array of u/int values.

## Environment
 - App: TX-Builder
 - Browser: All
 - Safe: All
 - Environment:
   - all

## Steps to reproduce
 1. Go to TX-Builder, using an ABI that requires uint, int or [uint], [int]
 2. Try to submit the form but an error will prevent with cause "overflow"

## Expected result
Transaction can be submited without issues

## Obtained result
Transaction is not possible to submit unless wrapping the values into strings

## Screenshots
![imagen](https://user-images.githubusercontent.com/25051234/167141580-67d2fb36-653a-43bf-9c3b-563043c9bc80.png)

**Comment by mikhailxyz** [comment]
I think for `uint` we have correct handling in place, but not for uint arrays https://github.com/gnosis/safe-react-apps/blob/150b5bc01f1cdc4374204dbc873c74c6db4f1c2f/apps/tx-builder/src/utils.ts#L57
