### ISSUE TITLE
[WalletConnect] App crashing when invalid message is signed (EIP-712)

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#520]
## Description
WC safe app is crashing when testing the EIP-712 & snapshot integration 

## Steps to reproduce
Using this [EIP-712 snapshot proposal](https://bafybeidecgkelmzrlrjl2et6jrwhn4c2vs5hsjluklphxdo2kueej43ony.on.fleek.co/#/fabien.eth/proposal/0xbe992f0a433d2dbe2e0cee579e5e1bdb625cdcb3a14357ea990c6cdc3e129991) connect via WC app on mainnet and vote on it (any option will do).

## Expected result
If there is something wrong with the proposal and voting will fail or not be possible because of that, handle the error so that the WC app does not crash.

## Obtained result
App is crashing.

https://user-images.githubusercontent.com/92332710/191059764-2214414f-d68f-48fb-9f93-d106fe60a2f4.mp4

**Comment by mikhailxyz** [comment]
This is tracked in https://github.com/safe-global/safe-apps-sdk/issues/363
