### ISSUE TITLE
[Drain Account, web core] remove or enhance dark theme for the app

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#527]
## Description

Drain account app looks no bueno while using the web interface with dark mode enabled, we should avoid this.

## Steps to reproduce
Open drain account safe app on web core while on dark mode.

## Expected result
For this first release I say we ignore dark mode completely on web core (tx-builder does not have it for example) and then introduce it properly for all of our safe apps if needed.

## Obtained result
<img width="1068" alt="Screenshot 2022-09-26 at 10 14 43" src="https://user-images.githubusercontent.com/92332710/192226949-ccaaaec1-7444-49f0-b771-ef5fc3163f0e.png">

**Comment by JagoFigueroa** [comment]
There might have been a problem when merging this ticket señor. I was having a look in [here](https://web-core.pages.dev/matic:0x6D04edC44F7C88faa670683036edC2F6FC10b86e/apps?appUrl=https%3A%2F%2Fapps.gnosis-safe.io%2Fdrain-safe) and dark theme for the drain app is still there.

**Comment by mikhailxyz** [comment]
@JagoFigueroa we haven't released the new version of the app yet

**Comment by JagoFigueroa** [comment]
got too used to testing on web that I went full monke 🤦
