### ISSUE TITLE
[Transaction queue, web core] queue overlapping with safe apps 

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#528]
## Description
The queue, when present, is overlapping with our safe apps making executing some action a bit uncomfortable.

## Steps to reproduce
While the transaction queue is visible, go to drain account app and try to perform a drain.

## Expected result
No overlapping as in legacy safe web (see screenshot on the right).

## Obtained result
Overlapping making perform a drain quite difficult (see screenshot on the left).

## Screenshots
<img width="1728" alt="Screenshot 2022-09-26 at 09 31 27" src="https://user-images.githubusercontent.com/92332710/192229326-1878a626-6f6d-4dfc-9807-9eb182e7a5e7.png">

Also on tx-builder:

<img width="1497" alt="Screenshot 2022-09-26 at 10 29 58" src="https://user-images.githubusercontent.com/92332710/192230036-f8c8a54b-f7ca-4ceb-9fea-48e2f407392c.png">

**Comment by mikhailxyz** [comment]
Could you please share the safe address and the resolution you used? I cannot reproduce it on a 4k screen

**Comment by JagoFigueroa** [comment]
señor @mikhailxyz ! I was able to reproduce this on my 16" macbook and also a 27" 2k screen. Any address should do but you but you can use [this one ](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/apps?appUrl=https%3A%2F%2Fapps.gnosis-safe.io%2Fdrain-safe) with a queued tx.
