### ISSUE TITLE
[$SAFE Claiming App] Self-delegation

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-react-apps#540]
## Overview

The delegate registry does not allow self-delegation but we do not validate the input field and provide no information leading to failing transactions. 

## Requirements

Validate that provided address does not equal your own Safe address 
Show error message "You cannot delegate to your own Safe address" 
Change text above input field (design is already updated)

## Designs

https://www.figma.com/file/igarLtnMhVtrYNOATmjJDc/Claim-S-Tokens-App?node-id=1%3A2

**Comment by usame-algan** [comment]
Can be tested as part of the new RC: https://github.com/safe-global/safe-react-apps/pull/543
