### ISSUE TITLE
Unable to interact with certain token contracts(USDT & WETH) on Arbitrum

### ISSUE THREAD

**Issue by L-tech** [safe-global/safe-react-apps#547]
## Environment
 - Browser:
 - Safe:
 - Environment:
   - production (Arbitrum)

## Steps to reproduce
 1. Go to web application -> click on transaction builder, enter the contract address of either USDT(0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9) or WETH(0x82aF49447D8a07e3bd95BD0d56f35241523fBab1), it get the ABI but unable to detect the implementation contract to interaction.
## Expected result
Show to option(prompt) to interact with implementation 
## Obtained result
Prompt does not come up to interact with implementation contract
## Screenshots
<img width="1440" alt="Screenshot 2022-10-07 at 12 46 27" src="https://user-images.githubusercontent.com/35797372/194550910-329a3709-6dde-42c3-8927-a621e4af818d.png">
<img width="1440" alt="Screenshot 2022-10-07 at 12 46 32" src="https://user-images.githubusercontent.com/35797372/194550940-30c363ac-e6b9-41d1-9974-c7b734875537.png">

**Comment by mikhailxyz** [comment]
We use two sources for contract ABIs:

1. [Our transaction service](https://safe-transaction.arbitrum.gnosis.io)
2. [Sourcify](https://sourcify.dev/)

In this case, the contract ABI seems unavailable in either of them.
1. https://safe-transaction.arbitrum.gnosis.io/api/v1/contracts/0x8b194bEae1d3e0788A1a35173978001ACDFba668/
2. https://repo.sourcify.dev/contracts/full_match/42161/0x8b194bEae1d3e0788A1a35173978001ACDFba668/

Please follow this guide for adding an ABI, or verify the contract on sourcify
https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi

**Comment by L-tech** [comment]
The contract addresses are 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1 - WETH & 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9 - USDT. The contract ABI is available here

https://safe-transaction.arbitrum.gnosis.io/api/v1/contracts/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9/
https://safe-transaction.arbitrum.gnosis.io/api/v1/contracts/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/

**Comment by mikhailxyz** [comment]
@L-tech The implementation contract ABIs are not available

**Comment by L-tech** [comment]
@mikhailxyz okay, please how do I add the ABIs for the implementation contract? Thanks
