### ISSUE TITLE
[safe-claiming-app]: Use tutis.eth snapshot space on goerli

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-react-apps#590]
## Overview
For testing the claiming app + widgets we should use our test snapshot space `tutis.eth` on goerli

## Requirements
- [x] Setup tutis.eth on goerli snapshot with same / similar setup to safe.eth on mainnet
- [x] Use tutis.eth on goerli for snapshot widget
- [x] Use tutis.eth on goerli for setting delegates via app

**Comment by liliya-soroka** [comment]
Verified
