### ISSUE TITLE
[safe-claiming-app]: voting power widget without any allocation / tokens

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-react-apps#591]
## Overview
Currently some dummy text is displayed for addresses without any allocated tokens.
We should show a meaningful message and remove the "buy tokens" button as this was just a placeholder.

## Requirements
- [x] Display instead:
```
*Become part of Safe’s future*
Help us unlocking ownership for everyone by joining the discussions in the SafeDAO Forum and our Discord.
```

**Comment by liliya-soroka** [comment]
Verified in Epic PR
