### ISSUE TITLE
Bookmark button disappears after a search is done in safe.global app

### ISSUE THREAD

**Issue by clemoon** [safe-global/safe-react-apps#609]
### Description
Bookmark button disappears after a search is done in safe.global app

### Steps to reproduce
Visit https://app.safe.global/eth:0xB88F61E6FbdA83fbfffAbE364112137480398018/apps and  type any letter in the search bar.
### Expected result
-The bookmark should be available for me to bookmark

### Obtained result
-The bookmarks disappear

**Comment by mikhailxyz** [comment]
closing this because we planned to fix this in the upcoming redesign
