### ISSUE TITLE
Custom app warning pop up visible for a short time when internal app is opened

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#619]
## Description
When opening an internal safe app like Drain Account or Tx-builder the custom app pop up is visible for a split second.

Note: At the time of opening this ticket this is only reproducible on rc 1.2.0 from the web team but should reach prod this week.

## Steps to reproduce
On the browser developer tools, set network speed to slow 3G or fast 3G to easier catch the pop up and open tx-builder safe app.

## Expected result
App is opened as usual.

## Obtained result
A warning pop up is shown for a split second.

https://user-images.githubusercontent.com/92332710/207391189-e107a437-eac3-45c6-893b-6710b297183e.mp4

**Comment by mikhailxyz** [comment]
Whoever gets to work on it - please check the discussion in the linked PR

**Comment by katspaugh** [comment]
I've made a small adjustment as per that thread and resolved it. Ready for QA.

**Comment by JagoFigueroa** [comment]
Closing this señor ticket as the linked PR was merged 😄
