### ISSUE TITLE
[WC v1] Show feedback and don't allow connection when it is from an unsupported chain

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#626]
## Description

It is possible to connect via wc app a safe on chain X with a Dapp with no support for a chain Y. We should not allow these connections.

## Steps to reproduce
 1. Go to WC safe app on Gnosis Chain (por example).
 2. Connect with a Dapp without support for that chain.

## Expected result
Connection not performed when not possible.

## Obtained result

https://user-images.githubusercontent.com/92332710/208078869-a952e312-b061-4223-98d2-3d835f27a95c.mp4

**Comment by mikhailxyz** [comment]
for wc1 this is not possible, we don't know what chain the app wants. Similarly, there's no warning in metamask when you connect to a dapp on a different chain

**Comment by JagoFigueroa** [comment]
I think you are right señor, I see that chainId always comes as 1 regardless of the chain :pepe-scream:

![Captura de pantalla 2022-12-16 a las 11 38 42](https://user-images.githubusercontent.com/92332710/208081863-93a63fff-9b87-454d-89fe-b70ad958dc0a.png)

Closing this
