### ISSUE TITLE
[Claiming app] Claim button not aligned + widget not linked

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-react-apps#627]
# Bug 1
The amount input and the claim button aren't aligned.

<img width="577" alt="Screenshot 2022-12-19 at 09 29 35" src="https://user-images.githubusercontent.com/381895/208381595-e2ad51f5-4e9b-4a2a-bed5-b3aacb41444f.png">

# Bug 2
The claiming widget on the Dashboard is not clickable. It could open the main Safe App when clicking on the amount. And when clicking on the Delegate – to the delegate editing screen.

**Comment by DiogoSoaress** [comment]
> And when clicking on the Delegate – to the delegate editing screen.

can we even achieve this without routes in the Claiming App?
