### ISSUE TITLE
Transaction builder: Simulate button is not hidden if Tx_simulation feature is off in the config service

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-react-apps#649]
1.turn off Tx_simulation feature in the config service for any chain
2. run tx builder
Current result: Simulate button is not hidden 
Expected result: Hide the button if the feature is off in the config service

**Comment by mikhailxyz** [comment]
safe apps do not use the config service and are not aware of chain features, currently chains where simulations aren't supported are hardcoded in the app code

**Comment by liliya-soroka** [comment]
Verified on staging
