### ISSUE TITLE
RAMP safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#655]
## Description
Looks like there have been some changes with the RAMP app (now requiring an [api key](https://docs.ramp.network/configuration/#hostapikey)) and we will need to update the integration from our end.

## Steps to reproduce
Open the RAMP safe app on mainnet

## Expected result
App opening and working as expected

## Obtained result
<img width="1724" alt="Screenshot 2023-01-30 at 12 08 35" src="https://user-images.githubusercontent.com/92332710/215464617-c66175ff-5b9d-46ff-ba5c-38d26b96abd2.png">

`{"response":["apiKey must be a string"],"status":400,"message":"Validation Exception","name":"ValidationException"}`

**Comment by mikhailxyz** [comment]
I've disabled the app on production for now
