### ISSUE TITLE
[WalletConnect] Enable connection without considering chain

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#763]
## Overview
After few months, even now `requiredChains` is an optional parameter, many connection providers didn't adapt. This makes impossible to connect some dApps to the Safe when using WalletConnect. Also a drawback for these providers to prevent adding this compatibility is because many other Wallet apps require explicitly the property, making the migration complex.
https://github.com/wagmi-dev/wagmi/issues/3027

Many providers accept a list of chains and always set the first one as required, even the others are set as optional. As the Safe can't guarantee that the required is always available the connection is automatically rejected.

## Requirements
 - Accept the connection whenever we detect the chain where the current Safe exists is present on `optionalChains`
 - Accept the connection even the required chain is not the current Safe chain.
 - Reject the connection if the current chain is not present either on required or optional chains.
 - In case the Safe is already using the required chain just accept the connection and let the user operate normally.
 - In case the Safe is connected to a chain different from the required one, warn the user to check that they are using the correct chain on the dApp side

**Comment by johannesmoormann** [comment]
will be addressed with https://github.com/safe-global/safe-wallet-web/pull/2535
