### ISSUE TITLE
Tx builder not loading correct ABI

### ISSUE THREAD

**Issue by czepluch** [safe-global/safe-react-apps#795]
## Description
I am following [this guide](https://hoprnet.notion.site/Claim-HOPR-Token-86caaa389d4a4ed9804d685917710834) to try to update my Safe fallback implementation. However, when I paste my Safe address into the Transaction Builder I don't see other options than `fallback` in the "Contract Method Selector". 

And the only content I see in the ABI is:
```
[
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_masterCopy",
        "type": "address"
      }
    ],
    "payable": false,
    "stateMutability": "nonpayable"
  },
  {
    "type": "fallback",
    "payable": true,
    "stateMutability": "payable"
  }
]
```

This leads be to believe that either there's something wrong with the TX builder or it's due to the fact that my Safe was one of the very first ever deployed. It is however updated to version 1.3.0 and has the `compatibilityFallbackHandler` 1.3.0 set to address 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4.

## Environment
 - Browser: Firefox
 - Wallet: Rainbow
 - Safe: Prefer not to say
 - Environment: Mainnet

**Comment by katspaugh** [comment]
AFAIK Tx builder fetches ABIs from etherscan and sourcify, and for proxy contracts such as it also offers to fetch the proxied implementation ABI. Don't think it's able to fetch mixins like fallback handlers. @dasanra please correct me if I'm wrong.

You might be able to just paste the fallback handler ABI manually though.

**Comment by czepluch** [comment]
Paste the fallback handler ABI where? As far as I understand I need to call a function on the safe to set the fallback handler.

**Comment by katspaugh** [comment]
Ah, I see now.

In the tx builder UI in the ABI field. You can paste the ABI of the “master copy” contract that your Safe account implements as a proxy. In your case, this contract: https://etherscan.io/address/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552#cod

Normally it should pick it up automatically.

**Comment by czepluch** [comment]
Ah, great. That worked. Thanks for the help. I will keep the issue open in case you want to look into why the TX builder isn't correctly fetching the ABI. If not, just close the issue please.

**Comment by katspaugh** [comment]
I'll close it because normally it picks up the proxy ABI w/o issue. I think it's really what you said, an edge case with an OG safe.

<img width="948" alt="Screenshot 2024-02-08 at 14 34 21" src="https://github.com/safe-global/safe-react-apps/assets/381895/5be64e2e-9eca-44d6-a397-77494d319f70">
