### ISSUE TITLE
Expand network support for Ramp Safe app

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-react-apps#811]
Currently the app is not visible on Optimism. There might be more chains that need to be added.

They support, among our chains:
Arbitrum
Avalanche
Celo
Ethereum
Linea
Optimism
Polygon
Polygon zkEVM
zkSync Era

Not supported:
Aurora
Scroll
XLayer

**Comment by katspaugh** [comment]
The app is now enabled on Optimism and Linea.
